# MUltiple Linear Regression

## Importing the main libraries

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### reading the dataset

In [7]:
df_data = pd.read_csv('50_Startups.csv')
df_data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [11]:
X = df_data.iloc[:,:4].values
y = df_data.iloc[:,4:].values

In [46]:
s = df_data.iloc[:,:4].values


array([0.0, 116983.8, 45173.06, 'California'], dtype=object)

#### Encode the categorical data

In [21]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
encoder = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[-1])],remainder='passthrough')
X =np.array(encoder.fit_transform(X))

In [25]:
X[:5]   # our categorical data has being encoded succesfully

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

#### splitting the dataset 

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=0)

###  Training the model

 the linear regression model takes care of the dummy variable trap
    and selecting features with the highest p value

In [31]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)


LinearRegression()

### carrying out predictions based on our models

In [39]:
pred_results = model.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((pred_results.reshape(len(pred_results),1),y_test.reshape(len(pred_results),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


In [40]:
!jt -l


Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl
