# Introduction

In this notebook we'll learn how to use NumPy to work with numerical data. 

<img src="https://i.imgur.com/dZ1XE9o.png" width=400>

## Importing the main modules

In [55]:
import numpy as np
from scipy import misc # import the image of a racoon
from PIL import Image  # module for reading image files 

# Understanding NumPy's ndarray

NumPy's most amazing feature is the **powerful** ndarray.

<img src="https://i.imgur.com/1IUqnxX.png" width=200>

#### 1- dimensional array(Vectors)

In [6]:
# creating a 1 directional array
array_1 = np.array([1,2,3,4])
array_1

array([1, 2, 3, 4])

In [7]:
print(f" aray_1 has {array_1.shape} shape")

 aray_1 has (4,) shape


In [8]:
# Accessing elements by index
array_1[2]

3

#### 2-Dimensional Arrays (Matrices)

In [9]:
array_2d = np.array([[1, 2, 3, 9], 
                     [5, 6, 7, 8]])

print(f'array_2d has {array_2d.ndim} dimensions')
print(f'Its shape is {array_2d.shape}')
print(f'It has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns')
print(array_2d)

array_2d has 2 dimensions
Its shape is (2, 4)
It has 2 rows and 4 columns
[[1 2 3 9]
 [5 6 7 8]]


In [10]:
# Access the 4th value in the 2nd row
array_2d[0,3]

9

In [12]:
# Access all the values in the first row except the last value
array_2d[0,:-1]

array([1, 2, 3])

#### N-Dimensional Arrays (Tensors)

**Challenge**: 
* How many dimensions does the array below have? 
* What is its shape (i.e., how many elements are along each axis)?
* Try to access the value `18` in the last line of code.
* Try to retrieve a 1 dimensional vector with the values `[97, 0, 27, 18]`
* Try to retrieve a (3,2) matrix with the values `[[ 0,  4], [ 7,  5], [ 5, 97]]`

*Hint*: You can use the `:` operator just as with Python Lists.

In [13]:
mystery_array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                        
                         [[7, 86, 6, 98],
                          [5, 1, 0, 4]],
                          
                          [[5, 36, 32, 48],
                           [97, 0, 27, 18]]])

# Note all the square brackets!
mystery_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 7, 86,  6, 98],
        [ 5,  1,  0,  4]],

       [[ 5, 36, 32, 48],
        [97,  0, 27, 18]]])

In [14]:
mystery_array.shape      # getting the shape of the array

(3, 2, 4)

In [17]:
mystery_array.ndim    # getting the dimensions

3

In [18]:
mystery_array[2,1,-1]  # accessing the value 18

18

In [34]:
# Try to retrieve a 1 dimensional vector with the values `[97, 0, 27, 18]`
access = mystery_array[2,1]
access

array([97,  0, 27, 18])

In [38]:
access_2 = mystery_array[:,:,1]
access_2

array([[ 1,  5],
       [86,  1],
       [36,  0]])

# NumPy Mini-Challenges

#### **Challenge 1**: Use [`.arange()`](https://numpy.org/devdocs/reference/generated/numpy.arange.html)to createa a vector `a` with values ranging from 10 to 29. You should get this:

`print(a)`

`[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]`

In [40]:
a = np.arange(10,30)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

#### **Challenge 2**: Use Python slicing techniques on `a` to:
* Create an array containing only the last 3 values of `a`
* Create a subset with only the 4th, 5th, and 6th values
* Create a subset of `a` containing all the values except for the first 12 (i.e., `[22, 23, 24, 25, 26, 27, 28, 29]`)
* Create a subset that only contains the even numbers (i.e, every second number)

In [44]:
a[-3:]   # containing the 3 last values

array([27, 28, 29])

In [45]:
a[4:7]

array([14, 15, 16])

In [48]:
a[12:]

array([22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
a[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### **Challenge 3**:Reverse the order of the values in `a`, so that the first element comes last:

`[29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10]`


If you need a hint, you can check out this part of the [NumPy beginner's guide](
https://numpy.org/devdocs/user/absolute_beginners.html#how-to-reverse-an-array)